-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_products" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "material" TEXT,
    "description" TEXT,
    "price_usd" REAL NOT NULL DEFAULT 0,
    "original_price_usd" REAL,
    "category" TEXT,
    "product_type" TEXT NOT NULL DEFAULT 'bracelets',
    "bead_size" TEXT,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "low_stock_threshold" INTEGER NOT NULL DEFAULT 5,
    "image_url" TEXT,
    "images" TEXT NOT NULL DEFAULT '[]',
    "badge" TEXT,
    "rating" REAL NOT NULL DEFAULT 0,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);
INSERT INTO "new_products" ("active", "badge", "bead_size", "category", "created_at", "description", "featured", "id", "image_url", "images", "low_stock_threshold", "material", "name", "original_price_usd", "price_usd", "rating", "review_count", "sort_order", "stock", "updated_at") SELECT "active", "badge", "bead_size", "category", "created_at", "description", "featured", "id", "image_url", "images", "low_stock_threshold", "material", "name", "original_price_usd", "price_usd", "rating", "review_count", "sort_order", "stock", "updated_at" FROM "products";
DROP TABLE "products";
ALTER TABLE "new_products" RENAME TO "products";
CREATE INDEX "products_active_idx" ON "products"("active");
CREATE INDEX "products_category_idx" ON "products"("category");
CREATE INDEX "products_product_type_idx" ON "products"("product_type");
CREATE INDEX "products_featured_idx" ON "products"("featured");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- Full catalogue: new stones and product types (pencils, pendants, rings,
-- bowls & plates, anklets, rudraksha, pyramid bracelets, certificates).
-- Prices are not set yet (0 = "price on request", not orderable) and stock
-- is 0; set both in Admin → Products. INSERT OR IGNORE never overwrites
-- a row that already exists.
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('clear-quartz','Clear Quartz','Crystal-clear quartz associated with focus and clarity.',10,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('moonstone','Moonstone','Glowing stone associated with intuition and new beginnings.',11,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('red-jasper','Red Jasper','Earthy red stone of strength and grounding.',12,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('green-aventurine','Green Aventurine','Shimmering green stone of luck and optimism.',13,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('green-jade','Green Jade','Treasured green stone of harmony and good fortune.',14,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('pyrite','Pyrite','Metallic ''fool''s gold'' associated with prosperity.',15,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('tiger-eye','Tiger Eye','Golden-brown banded stone of courage and focus.',16,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('black-sulimani','Black Sulimani','Banded black agate traditionally worn for protection.',17,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('black-agate','Black Agate','Smooth dark agate of balance and protection.',18,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('turquoise','Turquoise','Sky-blue stone of protection and good luck.',19,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('persian-turquoise','Persian Turquoise','Rich sky-blue turquoise associated with serenity.',20,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('sunstone','Sunstone','Sparkling orange stone of joy and vitality.',21,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('howlite','Howlite','White, grey-veined stone of patience and calm.',22,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('selenite','Selenite','Luminous white mineral used to cleanse other crystals.',23,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "categories" ("slug","name","description","sort_order","active","created_at") VALUES ('rudraksha','Rudraksha','Sacred Rudraksha seeds used for prayer and meditation.',24,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('amethyst-pencil','Amethyst Pencil (3 inch)','Natural Amethyst, polished six-sided point, approx. 3 inches','A polished six-sided Amethyst point, about 3 inches tall, that stands upright on a desk, shelf or altar. Amethyst is a violet quartz traditionally associated with calm, clarity and restful sleep. Each piece is natural, so colour, clarity and markings vary slightly from the photos.',0,'amethyst','pencils',NULL,0,2,'/assets/products/amethyst-pencil.jpg','["/assets/products/amethyst-pencil.jpg"]',0,0,1,0,100,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('clear-quartz-pencil','Clear Quartz Pencil (3 inch)','Natural Clear Quartz, polished six-sided point, approx. 3 inches','A polished six-sided Clear Quartz point, about 3 inches tall, that stands upright on a desk, shelf or altar. Clear Quartz is known as the ''master healer'' in crystal traditions and is associated with focus and clarity. Each piece is natural, so colour, clarity and markings vary slightly from the photos.',0,'clear-quartz','pencils',NULL,0,2,'/assets/products/clear-quartz-pencil.jpg','["/assets/products/clear-quartz-pencil.jpg"]',0,0,1,0,101,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('rose-quartz-pencil','Rose Quartz Pencil (3 inch)','Natural Rose Quartz, polished six-sided point, approx. 3 inches','A polished six-sided Rose Quartz point, about 3 inches tall, that stands upright on a desk, shelf or altar. Rose Quartz is a soft pink quartz traditionally associated with love, compassion and self-care. Each piece is natural, so colour, clarity and markings vary slightly from the photos.',0,'rose-quartz','pencils',NULL,0,2,'/assets/products/rose-quartz-pencil.jpg','["/assets/products/rose-quartz-pencil.jpg"]',0,0,1,0,102,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-obsidian-pencil','Black Obsidian Pencil (3 inch)','Natural Black Obsidian, polished six-sided point, approx. 3 inches','A polished six-sided Black Obsidian point, about 3 inches tall, that stands upright on a desk, shelf or altar. Black Obsidian is a glossy volcanic glass traditionally associated with grounding and protection. Each piece is natural, so colour, clarity and markings vary slightly from the photos.',0,'obsidian','pencils',NULL,0,2,'/assets/products/black-obsidian-pencil.jpg','["/assets/products/black-obsidian-pencil.jpg"]',0,0,1,0,103,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('moonstone-pencil','Moonstone Pencil (3 inch)','Natural Moonstone, polished six-sided point, approx. 3 inches','A polished six-sided Moonstone point, about 3 inches tall, that stands upright on a desk, shelf or altar. Moonstone shows a gentle, glowing sheen and is traditionally associated with intuition and new beginnings. Each piece is natural, so colour, clarity and markings vary slightly from the photos.',0,'moonstone','pencils',NULL,0,2,'/assets/products/moonstone-pencil.jpg','["/assets/products/moonstone-pencil.jpg"]',0,0,1,0,104,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('lapis-pendant','Lapis Lazuli Pendant','Natural Lapis Lazuli pendant with metal bail','A polished Lapis Lazuli pendant to wear on a chain or cord, close to the heart. Lapis Lazuli is a deep blue stone flecked with golden pyrite, associated with wisdom and truth. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'lapis-lazuli','pendants',NULL,0,2,'/assets/products/lapis-pendant.jpg','["/assets/products/lapis-pendant.jpg"]',0,0,1,0,105,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('amethyst-pendant','Amethyst Pendant','Natural Amethyst pendant with metal bail','A polished Amethyst pendant to wear on a chain or cord, close to the heart. Amethyst is a violet quartz traditionally associated with calm, clarity and restful sleep. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'amethyst','pendants',NULL,0,2,'/assets/products/amethyst-pendant.jpg','["/assets/products/amethyst-pendant.jpg"]',0,0,1,0,106,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('moonstone-pendant','Moonstone Pendant','Natural Moonstone pendant with metal bail','A polished Moonstone pendant to wear on a chain or cord, close to the heart. Moonstone shows a gentle, glowing sheen and is traditionally associated with intuition and new beginnings. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'moonstone','pendants',NULL,0,2,'/assets/products/moonstone-pendant.jpg','["/assets/products/moonstone-pendant.jpg"]',0,0,1,0,107,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('red-jasper-pendant','Red Jasper Pendant','Natural Red Jasper pendant with metal bail','A polished Red Jasper pendant to wear on a chain or cord, close to the heart. Red Jasper is an earthy red stone traditionally associated with strength, stamina and grounding. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'red-jasper','pendants',NULL,0,2,'/assets/products/red-jasper-pendant.jpg','["/assets/products/red-jasper-pendant.jpg"]',0,0,1,0,108,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-obsidian-pendant','Black Obsidian Pendant','Natural Black Obsidian pendant with metal bail','A polished Black Obsidian pendant to wear on a chain or cord, close to the heart. Black Obsidian is a glossy volcanic glass traditionally associated with grounding and protection. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'obsidian','pendants',NULL,0,2,'/assets/products/black-obsidian-pendant.jpg','["/assets/products/black-obsidian-pendant.jpg"]',0,0,1,0,109,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('green-aventurine-pendant','Green Aventurine Pendant','Natural Green Aventurine pendant with metal bail','A polished Green Aventurine pendant to wear on a chain or cord, close to the heart. Green Aventurine has a soft green shimmer and is traditionally known as a stone of luck and optimism. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'green-aventurine','pendants',NULL,0,2,'/assets/products/green-aventurine-pendant.jpg','["/assets/products/green-aventurine-pendant.jpg"]',0,0,1,0,110,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('green-jade-pendant','Green Jade Pendant','Natural Green Jade pendant with metal bail','A polished Green Jade pendant to wear on a chain or cord, close to the heart. Green Jade has been treasured for centuries and is traditionally associated with harmony and good fortune. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'green-jade','pendants',NULL,0,2,'/assets/products/green-jade-pendant.jpg','["/assets/products/green-jade-pendant.jpg"]',0,0,1,0,111,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('rose-quartz-pendant','Rose Quartz Pendant','Natural Rose Quartz pendant with metal bail','A polished Rose Quartz pendant to wear on a chain or cord, close to the heart. Rose Quartz is a soft pink quartz traditionally associated with love, compassion and self-care. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'rose-quartz','pendants',NULL,0,2,'/assets/products/rose-quartz-pendant.jpg','["/assets/products/rose-quartz-pendant.jpg"]',0,0,1,0,112,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('clear-quartz-pendant','Clear Quartz Pendant','Natural Clear Quartz pendant with metal bail','A polished Clear Quartz pendant to wear on a chain or cord, close to the heart. Clear Quartz is known as the ''master healer'' in crystal traditions and is associated with focus and clarity. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'clear-quartz','pendants',NULL,0,2,'/assets/products/clear-quartz-pendant.jpg','["/assets/products/clear-quartz-pendant.jpg"]',0,0,1,0,113,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('citrine-pendant','Citrine Pendant','Natural Citrine pendant with metal bail','A polished Citrine pendant to wear on a chain or cord, close to the heart. Citrine is a warm golden quartz traditionally associated with abundance, positivity and confidence. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'citrine','pendants',NULL,0,2,'/assets/products/citrine-pendant.jpg','["/assets/products/citrine-pendant.jpg"]',0,0,1,0,114,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('pyrite-pendant','Pyrite Pendant','Natural Pyrite pendant with metal bail','A polished Pyrite pendant to wear on a chain or cord, close to the heart. Pyrite, often called ''fool''s gold'', has a metallic sheen and is traditionally associated with prosperity and willpower. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'pyrite','pendants',NULL,0,2,'/assets/products/pyrite-pendant.jpg','["/assets/products/pyrite-pendant.jpg"]',0,0,1,0,115,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('tiger-eye-pendant','Tiger Eye Pendant','Natural Tiger Eye pendant with metal bail','A polished Tiger Eye pendant to wear on a chain or cord, close to the heart. Tiger Eye shows shifting golden-brown bands of light and is traditionally associated with courage and focus. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'tiger-eye','pendants',NULL,0,2,'/assets/products/tiger-eye-pendant.jpg','["/assets/products/tiger-eye-pendant.jpg"]',0,0,1,0,116,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-sulimani-pendant','Black Sulimani Pendant','Natural Black Sulimani pendant with metal bail','A polished Black Sulimani pendant to wear on a chain or cord, close to the heart. Black Sulimani (Sulemani Hakik) is a black agate with white bands, traditionally worn for protection. Each stone is natural and unique, so colour and pattern vary slightly from the photos.',0,'black-sulimani','pendants',NULL,0,2,'/assets/products/black-sulimani-pendant.jpg','["/assets/products/black-sulimani-pendant.jpg"]',0,0,1,0,117,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('clear-quartz-ring','Clear Quartz Ring','Natural Clear Quartz ring','A natural Clear Quartz ring for everyday wear. Clear Quartz is known as the ''master healer'' in crystal traditions and is associated with focus and clarity. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'clear-quartz','rings',NULL,0,2,'/assets/products/clear-quartz-ring.jpg','["/assets/products/clear-quartz-ring.jpg"]',0,0,1,0,118,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('rose-quartz-ring','Rose Quartz Ring','Natural Rose Quartz ring','A natural Rose Quartz ring for everyday wear. Rose Quartz is a soft pink quartz traditionally associated with love, compassion and self-care. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'rose-quartz','rings',NULL,0,2,'/assets/products/rose-quartz-ring.jpg','["/assets/products/rose-quartz-ring.jpg"]',0,0,1,0,119,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('lapis-ring','Lapis Lazuli Ring','Natural Lapis Lazuli ring','A natural Lapis Lazuli ring for everyday wear. Lapis Lazuli is a deep blue stone flecked with golden pyrite, associated with wisdom and truth. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'lapis-lazuli','rings',NULL,0,2,'/assets/products/lapis-ring.jpg','["/assets/products/lapis-ring.jpg"]',0,0,1,0,120,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('red-jasper-ring','Red Jasper Ring','Natural Red Jasper ring','A natural Red Jasper ring for everyday wear. Red Jasper is an earthy red stone traditionally associated with strength, stamina and grounding. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'red-jasper','rings',NULL,0,2,'/assets/products/red-jasper-ring.jpg','["/assets/products/red-jasper-ring.jpg"]',0,0,1,0,121,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-agate-ring','Black Agate Ring','Natural Black Agate ring','A natural Black Agate ring for everyday wear. Black Agate is a smooth, dark banded stone traditionally associated with balance and protection. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'black-agate','rings',NULL,0,2,'/assets/products/black-agate-ring.jpg','["/assets/products/black-agate-ring.jpg"]',0,0,1,0,122,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('turquoise-ring','Turquoise Ring','Natural Turquoise ring','A natural Turquoise ring for everyday wear. Turquoise is a sky-blue stone treasured across cultures and traditionally associated with protection and good luck. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'turquoise','rings',NULL,0,2,'/assets/products/turquoise-ring.jpg','["/assets/products/turquoise-ring.jpg"]',0,0,1,0,123,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('green-aventurine-ring','Green Aventurine Ring','Natural Green Aventurine ring','A natural Green Aventurine ring for everyday wear. Green Aventurine has a soft green shimmer and is traditionally known as a stone of luck and optimism. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'green-aventurine','rings',NULL,0,2,'/assets/products/green-aventurine-ring.jpg','["/assets/products/green-aventurine-ring.jpg"]',0,0,1,0,124,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('amethyst-ring','Amethyst Ring','Natural Amethyst ring','A natural Amethyst ring for everyday wear. Amethyst is a violet quartz traditionally associated with calm, clarity and restful sleep. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'amethyst','rings',NULL,0,2,'/assets/products/amethyst-ring.jpg','["/assets/products/amethyst-ring.jpg"]',0,0,1,0,125,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('green-jade-ring','Green Jade Ring','Natural Green Jade ring','A natural Green Jade ring for everyday wear. Green Jade has been treasured for centuries and is traditionally associated with harmony and good fortune. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'green-jade','rings',NULL,0,2,'/assets/products/green-jade-ring.jpg','["/assets/products/green-jade-ring.jpg"]',0,0,1,0,126,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('tiger-eye-ring','Tiger Eye Ring','Natural Tiger Eye ring','A natural Tiger Eye ring for everyday wear. Tiger Eye shows shifting golden-brown bands of light and is traditionally associated with courage and focus. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'tiger-eye','rings',NULL,0,2,'/assets/products/tiger-eye-ring.jpg','["/assets/products/tiger-eye-ring.jpg"]',0,0,1,0,127,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-obsidian-ring','Black Obsidian Ring','Natural Black Obsidian ring','A natural Black Obsidian ring for everyday wear. Black Obsidian is a glossy volcanic glass traditionally associated with grounding and protection. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'obsidian','rings',NULL,0,2,'/assets/products/black-obsidian-ring.jpg','["/assets/products/black-obsidian-ring.jpg"]',0,0,1,0,128,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('citrine-ring','Citrine Ring','Natural Citrine ring','A natural Citrine ring for everyday wear. Citrine is a warm golden quartz traditionally associated with abundance, positivity and confidence. Contact us for sizing help before you order. Natural stones vary slightly in colour and pattern.',0,'citrine','rings',NULL,0,2,'/assets/products/citrine-ring.jpg','["/assets/products/citrine-ring.jpg"]',0,0,1,0,129,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('money-magnet-bowl','Money Magnet Bowl','Crystal bowl with natural Pyrite','A decorative crystal bowl for your home or workspace, traditionally placed to invite abundance — a popular gift for new homes and businesses. Pyrite, often called ''fool''s gold'', is traditionally associated with prosperity and willpower. Contents and finish may vary slightly from the photos.',0,'pyrite','bowls-plates',NULL,0,2,'/assets/products/money-magnet-bowl.jpg','["/assets/products/money-magnet-bowl.jpg"]',0,0,1,0,130,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('selenite-plate','Selenite Plate','Natural Selenite charging plate','A round natural Selenite plate. Rest your bracelets, rings and tumbled stones on it to cleanse and recharge them — Selenite is traditionally used to clear other crystals. Selenite is soft and dissolves in water: keep it dry and wipe it clean with a soft cloth.',0,'selenite','bowls-plates',NULL,0,2,'/assets/products/selenite-plate.jpg','["/assets/products/selenite-plate.jpg"]',0,0,1,0,131,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('pyrite-anklet','Pyrite Anklet','Natural Pyrite beads, adjustable cord','A delicate anklet strung with small natural Pyrite beads. Pyrite, often called ''fool''s gold'', has a metallic sheen and is traditionally associated with prosperity and willpower. Remove before swimming or bathing to keep the cord in good condition.',0,'pyrite','anklets','4mm',0,2,'/assets/products/pyrite-anklet.jpg','["/assets/products/pyrite-anklet.jpg"]',0,0,1,0,132,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('black-obsidian-anklet','Black Obsidian Anklet','Natural Black Obsidian beads, adjustable cord','A delicate anklet strung with small natural Black Obsidian beads. Black Obsidian is a glossy volcanic glass traditionally associated with grounding and protection. Remove before swimming or bathing to keep the cord in good condition.',0,'obsidian','anklets','4mm',0,2,'/assets/products/black-obsidian-anklet.jpg','["/assets/products/black-obsidian-anklet.jpg"]',0,0,1,0,133,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('red-jasper-anklet','Red Jasper Anklet','Natural Red Jasper beads, adjustable cord','A delicate anklet strung with small natural Red Jasper beads. Red Jasper is an earthy red stone traditionally associated with strength, stamina and grounding. Remove before swimming or bathing to keep the cord in good condition.',0,'red-jasper','anklets','4mm',0,2,'/assets/products/red-jasper-anklet.jpg','["/assets/products/red-jasper-anklet.jpg"]',0,0,1,0,134,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('4-mukhi-rudraksha','4 Mukhi Rudraksha','Natural 4 Mukhi (four-faced) Rudraksha bead','A natural 4 Mukhi Rudraksha bead with four natural lines (faces) on its surface. In tradition it is associated with Lord Brahma and with knowledge, learning and clear communication. Can be worn on a thread or chain, or kept in your prayer space. Each bead is natural and unique in size and texture.',0,NULL,'rudraksha',NULL,0,2,'/assets/products/4-mukhi-rudraksha.jpg','["/assets/products/4-mukhi-rudraksha.jpg"]',0,0,1,0,135,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('5-mukhi-rudraksha','5 Mukhi Rudraksha','Natural 5 Mukhi (five-faced) Rudraksha bead','A natural 5 Mukhi Rudraksha bead — the most widely worn Rudraksha, with five natural lines (faces). In tradition it is associated with Lord Shiva (Kalagni Rudra) and with peace of mind and meditation. Can be worn on a thread or chain, or used in a mala. Each bead is natural and unique in size and texture.',0,NULL,'rudraksha',NULL,0,2,'/assets/products/5-mukhi-rudraksha.jpg','["/assets/products/5-mukhi-rudraksha.jpg"]',0,0,1,0,136,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('sunstone-pyramid-bracelet','Sunstone Pyramid Bracelet','Natural Sunstone beads, pyramid charm, elastic cord','A stretch bracelet of natural Sunstone beads finished with a pyramid charm. Sunstone glitters with warm orange flashes and is traditionally associated with joy and vitality. Fits most wrists; natural stones vary slightly in colour and pattern.',0,'sunstone','pyramid-bracelets','8mm',0,2,'/assets/products/sunstone-pyramid-bracelet.jpg','["/assets/products/sunstone-pyramid-bracelet.jpg"]',0,0,1,0,137,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('howlite-pyramid-bracelet','Howlite Pyramid Bracelet','Natural Howlite beads, pyramid charm, elastic cord','A stretch bracelet of natural Howlite beads finished with a pyramid charm. Howlite is a white stone with fine grey veins, traditionally associated with patience and calm. Fits most wrists; natural stones vary slightly in colour and pattern.',0,'howlite','pyramid-bracelets','8mm',0,2,'/assets/products/howlite-pyramid-bracelet.jpg','["/assets/products/howlite-pyramid-bracelet.jpg"]',0,0,1,0,138,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('persian-turquoise-pyramid-bracelet','Persian Turquoise Pyramid Bracelet','Natural Persian Turquoise beads, pyramid charm, elastic cord','A stretch bracelet of natural Persian Turquoise beads finished with a pyramid charm. Persian Turquoise is prized for its rich sky-blue colour and is traditionally associated with protection and serenity. Fits most wrists; natural stones vary slightly in colour and pattern.',0,'persian-turquoise','pyramid-bracelets','8mm',0,2,'/assets/products/persian-turquoise-pyramid-bracelet.jpg','["/assets/products/persian-turquoise-pyramid-bracelet.jpg"]',0,0,1,0,139,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('mix-pyramid-bracelet','Mixed Crystal Pyramid Bracelet','Natural Mixed Crystal beads, pyramid charm, elastic cord','A stretch bracelet of natural mixed crystal beads finished with a pyramid charm. A mix of gemstones combined in one piece, each with its own colour and character. Fits most wrists; natural stones vary slightly in colour and pattern.',0,NULL,'pyramid-bracelets','8mm',0,2,'/assets/products/mix-pyramid-bracelet.jpg','["/assets/products/mix-pyramid-bracelet.jpg"]',0,0,1,0,140,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT OR IGNORE INTO "products" ("id","name","material","description","price_usd","category","product_type","bead_size","stock","low_stock_threshold","image_url","images","rating","review_count","active","featured","sort_order","created_at","updated_at") VALUES ('authenticity-certificate','Certificate of Authenticity','Printed certificate of authenticity','A printed certificate confirming the natural stone of your Arise Numero purchase — useful for gifting or for your own records. Add it to your order alongside the crystal it is for, and mention that item in the order notes or contact us after ordering.',0,NULL,'certificates',NULL,0,2,'/assets/products/authenticity-certificate.jpg','["/assets/products/authenticity-certificate.jpg"]',0,0,1,0,141,CAST(strftime('%s','now') AS INTEGER) * 1000,CAST(strftime('%s','now') AS INTEGER) * 1000);
